/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as authIndexRouteImport } from './routes/(auth)/index'
import { Route as appDecksIndexRouteImport } from './routes/(app)/decks/index'
import { Route as appDecksIdRouteImport } from './routes/(app)/decks/$id'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const authIndexRoute = authIndexRouteImport.update({
  id: '/(auth)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appDecksIndexRoute = appDecksIndexRouteImport.update({
  id: '/decks/',
  path: '/decks/',
  getParentRoute: () => appRouteRoute,
} as any)
const appDecksIdRoute = appDecksIdRouteImport.update({
  id: '/decks/$id',
  path: '/decks/$id',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof appSettingsRoute
  '/': typeof authIndexRoute
  '/decks/$id': typeof appDecksIdRoute
  '/decks/': typeof appDecksIndexRoute
}
export interface FileRoutesByTo {
  '/settings': typeof appSettingsRoute
  '/': typeof authIndexRoute
  '/decks/$id': typeof appDecksIdRoute
  '/decks': typeof appDecksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/settings': typeof appSettingsRoute
  '/(auth)/': typeof authIndexRoute
  '/(app)/decks/$id': typeof appDecksIdRoute
  '/(app)/decks/': typeof appDecksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/settings' | '/' | '/decks/$id' | '/decks/'
  fileRoutesByTo: FileRoutesByTo
  to: '/settings' | '/' | '/decks/$id' | '/decks'
  id:
    | '__root__'
    | '/(app)'
    | '/(app)/settings'
    | '/(auth)/'
    | '/(app)/decks/$id'
    | '/(app)/decks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  authIndexRoute: typeof authIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/': {
      id: '/(auth)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/decks/': {
      id: '/(app)/decks/'
      path: '/decks'
      fullPath: '/decks/'
      preLoaderRoute: typeof appDecksIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/decks/$id': {
      id: '/(app)/decks/$id'
      path: '/decks/$id'
      fullPath: '/decks/$id'
      preLoaderRoute: typeof appDecksIdRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appSettingsRoute: typeof appSettingsRoute
  appDecksIdRoute: typeof appDecksIdRoute
  appDecksIndexRoute: typeof appDecksIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appSettingsRoute: appSettingsRoute,
  appDecksIdRoute: appDecksIdRoute,
  appDecksIndexRoute: appDecksIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  authIndexRoute: authIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
